### ISSUE TITLE
Ctrl + Mouse Wheel to Zoom For Flow and Call Views is Broken On The Win64 Build

### ISSUE THREAD

**Issue by tekwizz123** [relyze-ltd/Relyze-3-Beta#8]
At the moment the only way to zoom in and out in the graph view appears to be with the CTL+ or CTL- key combinations. There isn't a way to zoom in using the mouse or touch pad itself. Considering this is available in pretty much every other disassembler on the market today, I'd imagine this feature would be a sticking point for a lot of users if it isn't included in the final release of Relyze 3.

**Comment by stephenfewer** [comment]
We support holding the Ctrl key to let you zoom in and out via the mouse wheel.

Pinch to zoom support via a touch pad would be nice, I'll add this to the wish list.

Thanks for the feedback.

**Comment by tekwizz123** [comment]
Hmm I wasn't able to get this working in Relyze 3 Beta. Using a laptop with an external mouse, can confirm that it will scroll up and down in every other application and CTL+ and CTL- work, but scrolling with the mouse whilst holding the CTL key does not work.

**Comment by stephenfewer** [comment]
Ok I can reproduce here, mouse scrolling and ctrl + mouse wheel to zoom for the flow and call views is broken in the win64 build but working in a win32 build for Relyze v3.

This will be resolved in the upcoming 3.0.1 release in a few weeks.

Thanks for the bug reporting! 👍

**Comment by tekwizz123** [comment]
Thanks, meant to say I was using a 64 bit build, sorry for not including that earlier but glad you were able to identify where the issue is :)

**Comment by tekwizz123** [comment]
Can confirm this has been fixed on Beta version 3.0.1, thanks for the fix @stephenfewer!
